DESTDIR:=/data/Thesis/figures/ChapterSigProperties/blikMVA/
DESTDIR:=~/www/vbfHbb/blikelihood/

all:

copyplots:
	cp plots/EvIntDiscriminant_variablesIn_NOM.pdf $(DESTDIR)
	cp plots/EvIntDiscriminant_variablesIn_VBF.pdf $(DESTDIR)
	cp plots/EvIntDiscriminant_variablesOutCERN-3a_NOM.pdf $(DESTDIR)
	cp plots/EvIntDiscriminant_variablesOutCERN-3a_VBF.pdf $(DESTDIR)
	cp plots/EvIntDiscriminant_variablesOutCERN-2-new_NOM.pdf $(DESTDIR)
	cp plots/EvIntDiscriminant_variablesOutCERN-2-new_VBF.pdf $(DESTDIR)
	cp plots/performance-3_NOM.pdf $(DESTDIR)
	cp plots/performance-3_VBF.pdf $(DESTDIR)
	cp plots/EvIntDiscriminant_variablesOutCERN-4_NOM.pdf $(DESTDIR)
	cp plots/EvIntDiscriminant_variablesOutCERN-4_VBF.pdf $(DESTDIR)
	#
	cp plots/performanceAlt-3_NOM.pdf $(DESTDIR)
	cp plots/EvIntDiscriminant_variablesInAlt_NOM.pdf $(DESTDIR)
	cp plots/EvIntDiscriminant_variablesOutAlt-2-new_NOM.pdf $(DESTDIR)
	cp plots/EvIntDiscriminant_variablesOutAlt-3a_NOM.pdf $(DESTDIR)
	cp plots/EvIntDiscriminant_variablesOutAlt-4_NOM.pdf $(DESTDIR)
